version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - "9004:9004"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 9004
